#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;
#if defined(__cplusplus)
extern "C" {
#endif

extern void _AMPA_NMDA_reg(void);
extern void _AMPA_NMDA_STP_reg(void);
extern void _AMPA_NMDA_STP_LTP_reg(void);
extern void _AMPA_NMDA_STP_LTP_PN2PV_reg(void);
extern void _AMPA_NMDA_STP_LTP_tone2PN_reg(void);
extern void _AMPA_NMDA_STP_LTP_tone2PV_reg(void);
extern void _GABA_AB_reg(void);
extern void _GABA_AB_STP_reg(void);
extern void _Gfluct_exc_reg(void);
extern void _Gfluct_inh_reg(void);
extern void _Gfluct_new_exc_reg(void);
extern void _Gfluct_new_inh_reg(void);
extern void _bg2pyr_reg(void);
extern void _cadyn_reg(void);
extern void _cal2_reg(void);
extern void _cal2CA3_reg(void);
extern void _capool_reg(void);
extern void _capoolCA3_reg(void);
extern void _cas_reg(void);
extern void _cat_reg(void);
extern void _currentclamp_reg(void);
extern void _function_TMonitor_reg(void);
extern void _h_reg(void);
extern void _hCA3_reg(void);
extern void _halfgap_reg(void);
extern void _im_reg(void);
extern void _imCA3_reg(void);
extern void _kadist_reg(void);
extern void _kaprox_reg(void);
extern void _kca_reg(void);
extern void _kdrCA3_reg(void);
extern void _kdrca1_reg(void);
extern void _kdrca1DA_reg(void);
extern void _kdrinter_reg(void);
extern void _leak_reg(void);
extern void _leakCA3_reg(void);
extern void _leakDA_reg(void);
extern void _leakinter_reg(void);
extern void _na3_reg(void);
extern void _na3DA_reg(void);
extern void _nainter_reg(void);
extern void _nap_reg(void);
extern void _napCA3_reg(void);
extern void _nat_reg(void);
extern void _natCA3_reg(void);
extern void _pv2pv_reg(void);
extern void _pv2pyr_reg(void);
extern void _pv2som_reg(void);
extern void _pyr2pv_reg(void);
extern void _pyr2pyr_reg(void);
extern void _pyr2som_reg(void);
extern void _pyr2vip_reg(void);
extern void _sahp_reg(void);
extern void _sahpCA3_reg(void);
extern void _sahpNE_reg(void);
extern void _som2pv_reg(void);
extern void _som2pyr_reg(void);
extern void _tone2pv_reg(void);
extern void _tone2pyr_reg(void);
extern void _tone2vip_reg(void);
extern void _vecevent_coreneuron_reg(void);

void modl_reg() {
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");
    fprintf(stderr, " \"modfiles_core//AMPA_NMDA.mod\"");
    fprintf(stderr, " \"modfiles_core//AMPA_NMDA_STP.mod\"");
    fprintf(stderr, " \"modfiles_core//AMPA_NMDA_STP_LTP.mod\"");
    fprintf(stderr, " \"modfiles_core//AMPA_NMDA_STP_LTP_PN2PV.mod\"");
    fprintf(stderr, " \"modfiles_core//AMPA_NMDA_STP_LTP_tone2PN.mod\"");
    fprintf(stderr, " \"modfiles_core//AMPA_NMDA_STP_LTP_tone2PV.mod\"");
    fprintf(stderr, " \"modfiles_core//GABA_AB.mod\"");
    fprintf(stderr, " \"modfiles_core//GABA_AB_STP.mod\"");
    fprintf(stderr, " \"modfiles_core//Gfluct_exc.mod\"");
    fprintf(stderr, " \"modfiles_core//Gfluct_inh.mod\"");
    fprintf(stderr, " \"modfiles_core//Gfluct_new_exc.mod\"");
    fprintf(stderr, " \"modfiles_core//Gfluct_new_inh.mod\"");
    fprintf(stderr, " \"modfiles_core//bg2pyr.mod\"");
    fprintf(stderr, " \"modfiles_core//cadyn.mod\"");
    fprintf(stderr, " \"modfiles_core//cal2.mod\"");
    fprintf(stderr, " \"modfiles_core//cal2CA3.mod\"");
    fprintf(stderr, " \"modfiles_core//capool.mod\"");
    fprintf(stderr, " \"modfiles_core//capoolCA3.mod\"");
    fprintf(stderr, " \"modfiles_core//cas.mod\"");
    fprintf(stderr, " \"modfiles_core//cat.mod\"");
    fprintf(stderr, " \"modfiles_core//currentclamp.mod\"");
    fprintf(stderr, " \"modfiles_core//function_TMonitor.mod\"");
    fprintf(stderr, " \"modfiles_core//h.mod\"");
    fprintf(stderr, " \"modfiles_core//hCA3.mod\"");
    fprintf(stderr, " \"modfiles_core//halfgap.mod\"");
    fprintf(stderr, " \"modfiles_core//im.mod\"");
    fprintf(stderr, " \"modfiles_core//imCA3.mod\"");
    fprintf(stderr, " \"modfiles_core//kadist.mod\"");
    fprintf(stderr, " \"modfiles_core//kaprox.mod\"");
    fprintf(stderr, " \"modfiles_core//kca.mod\"");
    fprintf(stderr, " \"modfiles_core//kdrCA3.mod\"");
    fprintf(stderr, " \"modfiles_core//kdrca1.mod\"");
    fprintf(stderr, " \"modfiles_core//kdrca1DA.mod\"");
    fprintf(stderr, " \"modfiles_core//kdrinter.mod\"");
    fprintf(stderr, " \"modfiles_core//leak.mod\"");
    fprintf(stderr, " \"modfiles_core//leakCA3.mod\"");
    fprintf(stderr, " \"modfiles_core//leakDA.mod\"");
    fprintf(stderr, " \"modfiles_core//leakinter.mod\"");
    fprintf(stderr, " \"modfiles_core//na3.mod\"");
    fprintf(stderr, " \"modfiles_core//na3DA.mod\"");
    fprintf(stderr, " \"modfiles_core//nainter.mod\"");
    fprintf(stderr, " \"modfiles_core//nap.mod\"");
    fprintf(stderr, " \"modfiles_core//napCA3.mod\"");
    fprintf(stderr, " \"modfiles_core//nat.mod\"");
    fprintf(stderr, " \"modfiles_core//natCA3.mod\"");
    fprintf(stderr, " \"modfiles_core//pv2pv.mod\"");
    fprintf(stderr, " \"modfiles_core//pv2pyr.mod\"");
    fprintf(stderr, " \"modfiles_core//pv2som.mod\"");
    fprintf(stderr, " \"modfiles_core//pyr2pv.mod\"");
    fprintf(stderr, " \"modfiles_core//pyr2pyr.mod\"");
    fprintf(stderr, " \"modfiles_core//pyr2som.mod\"");
    fprintf(stderr, " \"modfiles_core//pyr2vip.mod\"");
    fprintf(stderr, " \"modfiles_core//sahp.mod\"");
    fprintf(stderr, " \"modfiles_core//sahpCA3.mod\"");
    fprintf(stderr, " \"modfiles_core//sahpNE.mod\"");
    fprintf(stderr, " \"modfiles_core//som2pv.mod\"");
    fprintf(stderr, " \"modfiles_core//som2pyr.mod\"");
    fprintf(stderr, " \"modfiles_core//tone2pv.mod\"");
    fprintf(stderr, " \"modfiles_core//tone2pyr.mod\"");
    fprintf(stderr, " \"modfiles_core//tone2vip.mod\"");
    fprintf(stderr, " \"modfiles_core//vecevent_coreneuron.mod\"");
    fprintf(stderr, "\n");
  }
  _AMPA_NMDA_reg();
  _AMPA_NMDA_STP_reg();
  _AMPA_NMDA_STP_LTP_reg();
  _AMPA_NMDA_STP_LTP_PN2PV_reg();
  _AMPA_NMDA_STP_LTP_tone2PN_reg();
  _AMPA_NMDA_STP_LTP_tone2PV_reg();
  _GABA_AB_reg();
  _GABA_AB_STP_reg();
  _Gfluct_exc_reg();
  _Gfluct_inh_reg();
  _Gfluct_new_exc_reg();
  _Gfluct_new_inh_reg();
  _bg2pyr_reg();
  _cadyn_reg();
  _cal2_reg();
  _cal2CA3_reg();
  _capool_reg();
  _capoolCA3_reg();
  _cas_reg();
  _cat_reg();
  _currentclamp_reg();
  _function_TMonitor_reg();
  _h_reg();
  _hCA3_reg();
  _halfgap_reg();
  _im_reg();
  _imCA3_reg();
  _kadist_reg();
  _kaprox_reg();
  _kca_reg();
  _kdrCA3_reg();
  _kdrca1_reg();
  _kdrca1DA_reg();
  _kdrinter_reg();
  _leak_reg();
  _leakCA3_reg();
  _leakDA_reg();
  _leakinter_reg();
  _na3_reg();
  _na3DA_reg();
  _nainter_reg();
  _nap_reg();
  _napCA3_reg();
  _nat_reg();
  _natCA3_reg();
  _pv2pv_reg();
  _pv2pyr_reg();
  _pv2som_reg();
  _pyr2pv_reg();
  _pyr2pyr_reg();
  _pyr2som_reg();
  _pyr2vip_reg();
  _sahp_reg();
  _sahpCA3_reg();
  _sahpNE_reg();
  _som2pv_reg();
  _som2pyr_reg();
  _tone2pv_reg();
  _tone2pyr_reg();
  _tone2vip_reg();
  _vecevent_coreneuron_reg();
}

#if defined(__cplusplus)
}
#endif
